var departments = {
    '0': 'Khoa Ngoại ngữ',
    '1': 'Khoa Mỹ thuật công nghiệp',
    '2': 'Khoa Kế toán',
    '3': 'Khoa Khoa học xã hội và Nhân văn',
    '4': 'Khoa Điện - Điện tử',
    '5': 'Khoa Công nghệ thông tin',
    '6': 'Khoa Khoa học ứng dụng',
    '7': 'Khoa Quản trị kinh doanh',
    '8': 'Khoa Kỹ thuật công trình',
    '9': 'Khoa Môi trường và Bảo hộ lao động',
    'A': 'Khoa Lao động công đoàn',
    'B': 'Khoa Tài chính - Ngân hàng',
    'C': 'Khoa Toán - Thống kê',
    'D': 'Khoa Khoa học thể thao',
    'E': 'Khoa Luật',
    'H': 'Khoa Dược',
    'G': 'Phòng Công tác học sinh sinh viên',
    'K': 'Phòng Đại học',
    'M': 'Phòng Sau đại học',
    'N': 'Phòng Điện toán và máy tính',
    'P': 'Phòng khảo thí và kiểm định chất lượng',
    'J': 'Phòng Tài chính',
    'O': 'TDT Creative Language Center',
    'I': 'Trung tâm tin học',
    'L': 'Trung tâm đào tạo và phát triển xã hội',
    'R': 'Trung tâm phát triển Khoa học quản lý và Ứng dụng công nghệ',
    'Q': 'Trung tâm hợp tác doanh nghiệp và cựa sinh viên',
    'W': 'Trung tâm ngoại ngữ - tin học - bồi dưỡng văn hóa',
    'X': 'Viện chính sách kinh tế và kinh doanh',
    'Y': 'Khoa giáo dục quốc tế'
}
module.exports = {departmentCodes: departments}
